# Generated by Django 6.0 on 2025-12-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MTDNATree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genetics.mtdnatree')),
            ],
            options={
                'verbose_name': 'mtDNA Haplogroup',
                'verbose_name_plural': 'mtDNA Haplogroups',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='genetics.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='genetics.province')),
            ],
            options={
                'unique_together': {('name', 'province')},
            },
        ),
        migrations.CreateModel(
            name='YDNATree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genetics.ydnatree')),
            ],
            options={
                'verbose_name': 'Y-DNA Haplogroup',
                'verbose_name_plural': 'Y-DNA Haplogroups',
            },
        ),
        migrations.CreateModel(
            name='GeneticSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genetics.city')),
                ('mt_dna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genetics.mtdnatree')),
                ('y_dna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genetics.ydnatree')),
            ],
            options={
                'verbose_name': 'Genetic Sample',
                'verbose_name_plural': 'Genetic Samples',
            },
        ),
    ]
