# Generated by Django 6.0 on 2025-12-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_year', models.IntegerField(help_text='Use negative values for BCE (e.g., -500 = 500 BCE)')),
                ('end_year', models.IntegerField(help_text='Use negative values for BCE')),
            ],
            options={
                'verbose_name': 'Historical Period',
                'verbose_name_plural': 'Historical Periods',
                'ordering': ['start_year'],
            },
        ),
        migrations.RemoveField(
            model_name='geneticsample',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='geneticsample',
            name='historical_period',
            field=models.ForeignKey(blank=True, help_text='Approximate time period of the individual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genetics.historicalperiod'),
        ),
    ]
