# Generated by Django 6.0 on 2025-12-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0002_historicalperiod_remove_geneticsample_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
    ]
