# Generated by Django 6.0 on 2025-12-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0004_geneticsample_country_geneticsample_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticsample',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genetics.city'),
        ),
    ]
