# Generated by Django 5.2.7 on 2025-12-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0005_alter_geneticsample_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticsample',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Number of individuals represented by this sample'),
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provinces', models.ManyToManyField(blank=True, related_name='ethnicities', to='genetics.province')),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
            },
        ),
        migrations.AddField(
            model_name='geneticsample',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genetics.ethnicity'),
        ),
    ]
